### ISSUE TITLE
Inference script or inference cpp 

### ISSUE THREAD

**Issue by abhigoku10** [Vertical-Beach/ByteTrack-cpp#2]
@medalotte  thanks for hsaring the code base it was really helpful , do u have the script or inference file so that we can pass the input video and visualize the results 

Thanks in advance

**Comment by medalotte** [comment]
Hi @abhigoku10, we don't have any inference scripts or visualizers that we can make publicly available at this time, so please try to implement them, for example, using [our test program](https://github.com/Vertical-Beach/ByteTrack-cpp/blob/main/test/test_BYTETracker.cpp#L120-L139) as a reference.
