### ISSUE TITLE
Setting `-march=native` causes problems with clang

### ISSUE THREAD

**Issue by derpda** [Vertical-Beach/ByteTrack-cpp#4]
First of all thank you for putting together this library, specifically without the attached object detection.

## Issue

When cross-compiling this project with clang 12.0.9 for Android arm64-v8a, the compiler option `-march=native` set here https://github.com/Vertical-Beach/ByteTrack-cpp/blob/e6ee5a1485bedd24e2b8d6411be5d8fef63a6c3e/CMakeLists.txt#L10
causes compiler check 
https://github.com/Vertical-Beach/ByteTrack-cpp/blob/e6ee5a1485bedd24e2b8d6411be5d8fef63a6c3e/CMakeLists.txt#L15
to fail.
Generally, `-march=native` is an optimization that [limits portability](https://stackoverflow.com/questions/52653025/why-is-march-native-used-so-rarely), as shown in this case.
It would be best to remove that optimization directive and leave it to users of the library to apply as needed.

I'll post a PR removing this single option.

**Comment by medalotte** [comment]
Hi @derpda.
Thanks for pointing this out. There is no problem about this, I merged the PR.
