### ISSUE TITLE
Missing header includes

### ISSUE THREAD

**Issue by derpda** [Vertical-Beach/ByteTrack-cpp#6]
Thank you for answering the previous issue so quickly!

The cmake configure step now works flawlessly =)
However, I ran into the next minor issue, which has to do with standard library includes.

## Issue
Some headers for standard library features were not included where they were needed.
For example, `<vector>` was never explicitly included in the library, but is extensively used.
Depending on the implementation of the standard library this can work, but in my case it did not.

I will once again make a PR for this!

**Comment by medalotte** [comment]
@derpda Sorry for the delay in checking. Thanks for the fixes!
