### ISSUE TITLE
Automatic Eigen download

### ISSUE THREAD

**Issue by derpda** [Vertical-Beach/ByteTrack-cpp#9]
Sorry for adding so many issues in such a short time =D

## Issue
ByteTrack depends on Eigen, but relies on it being installed in the system of the user.

That is not commonly the case, and since Eigen is a open-source header-only library, we can take care of downloading it in CMake.

For example:
```cmake
set(EIGEN_VERSION 3.3)
find_package(Eigen3 ${EIGEN_VERSION} QUIET)
if(NOT EIGEN3_FOUND)
  set(BUILD_TESTING OFF CACHE INTERNAL "")
  FetchContent_Declare(eigen
    GIT_REPOSITORY  https://gitlab.com/libeigen/eigen.git
    GIT_TAG         ${EIGEN_VERSION}
    GIT_SHALLOW     ON)
  FetchContent_MakeAvailable(eigen)
  unset(BUILD_TESTING CACHE)
endif()
```
This will download the Eigen librarry, disable its test build and make the `Eigen3::Eigen` target available.
Internally this uses `add_subdirectory()`, thus we do not need `find_package` again after the download.

Since Eigen is a header-only library, the impact on configure/compile time is minimal and performance is not affected.

**Comment by medalotte** [comment]
Thanks!
